#ifndef CONST_H
#define CONST_H

#define HANDLER_CORE_BLUETOOTH_LOCAL_ADAPTER 1
#define HANDLER_CORE_BLUETOOTH_LOCAL_ADAPTER_ERROR 2
#define HANDLER_CORE_BLUETOOTH_REMOTE_DEVICE 3
#define HANDLER_CORE_BLUETOOTH_REMOTE_DEVICE_ERROR 4
#define HANDLER_CORE_GUI_SEARCH_REMOTE_DEVICE 5
#define HANDLER_CORE_GUI_SEARCH_REMOTE_DEVICE_ERROR 6
#define HANDLER_CORE_REQUEST_SEARCH_REMOTE_DEVICE 7 // "bluetooth.h"
#define HANDLER_CORE_LOAD_POINTER 8
#define HANDLER_CORE_DIALOG_SELECT_LIST 9

#define EMIT_DIALOG_PROGRESS_SHOW 1
#define EMIT_DIALOG_SELECT_LIST_SHOW 2
#define EMIT_DIALOG_PROGRESS_STOP 3

#endif // CONST_H
